### ISSUE TITLE
ApplicationCard.jsx - implementacja

### ISSUE THREAD

**Issue by piotrek-b** [lewan0996/SlaveMarketWeb#53]
Należy zaimplementować komponent ApplicationCard - powinien on otrzymać aplikację jako prop i wyświetlić ogólne informacje na jego temat (m. in. avatar, imię i nazwisko, powiązane ogłoszenie, datę oraz skrócony opis).
Powinny zostać również wyświetlone przyciski do akceptacji/odrzucenia, usunięcia aplikacji oraz kontaktu z osobą aplikującą.

**Comment by piotrek-b** [comment]
@Lukastq jaki jest status tego taska?

**Comment by Lukastq** [comment]
Stworzyłem pull request'a do 3 tasków.

2018-05-12 11:54 GMT+02:00 Piotr <notifications@github.com>:
