### ISSUE TITLE
NavBar.jsx - implementacja

### ISSUE THREAD

**Issue by piotrek-b** [lewan0996/SlaveMarketWeb#60]
Należy zaimplementować komponent NavBar.
Jeśli użytkownik jest zalogowany, powinien wyświetlić się przycisk z jego ogłoszeniami oraz przycisk pozwalający przejść do konta, wraz ze zdjęciem.
Jeśli nie zalogowany, powinna wyświetlić się sekcja z polami tekstowymi na login/email oraz hasło, by się zalogować, lub przycisk służący do przejścia do formularza rejestracyjnego.

**Comment by piotrek-b** [comment]
@kkielczewski jaki jest status tego taska?

**Comment by kkielczewski** [comment]
Nie mogę skończyć taska bo nie mogę sprawdzić czy użytkownik jest zalogowany ale jak chcesz zobaczyć jak to na razie wygląda to masz tu plik:
[NavBar.zip](https://github.com/lewan0996/SlaveMarketWeb/files/1997576/NavBar.zip)

**Comment by piotrek-b** [comment]
Możesz stworzyć zmienną 'isLoggedIn' i przestawiać ją na true lub false, po połączeniu z API zrobimy poprawkę.
Wszelkie zmiany proszę pushuj na repo
