### ISSUE TITLE
SearchBar.jsx - implementacja

### ISSUE THREAD

**Issue by piotrek-b** [lewan0996/SlaveMarketWeb#61]
Należy zaimplementować komponent SearchBar - pole tekstowe, służące do przeszukiwania danej zawartości, wywołujące metodę podaną jako callback w przypadku zmiany zawartości pola.

**Comment by piotrek-b** [comment]
@kkielczewski jaki jest status tego taska?

**Comment by kkielczewski** [comment]
Zrobiłem push'a choć nie mam pewności czy dobrze zrozumiałem co oznacza 'zmiana zawartości pola' więc przyjąłem, że trzeba wcisnąć enter by wywołać funkcję.

**Comment by piotrek-b** [comment]
'Zmiana wartości pola' = onChange.
Ok, jeśli task jest dla Ciebie gotowy to zrób PR na developa.
